### ISSUE TITLE
Animation for logo too fast.

### ISSUE THREAD

**Issue by bigmosi** [aboongm/Portfolio-setup-and-mobile-version-skeleton#7]
https://github.com/aboongm/Portfolio-setup-and-mobile-version-skeleton/blob/521b971604a0491eda7ab232b692338b16b0ba49/styles.css#L451-L467

**Comment by bigmosi** [comment]
Make animations a little bit slow.

**Comment by aboongm** [comment]
@bigmosi ok. I will make the animation-duration to 2s from 1s.

**Comment by gids-dadi** [comment]
Great effort and on time too.

**Comment by bengigo** [comment]
Good work so far 👍

**Comment by aboongm** [comment]
The issue is addressed.
